name: ci

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch: # Run it if sync doesn't update fcitx5 part (i.e. only updates google/mozc)

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      CC: clang
      CXX: clang++
    steps:
      - name: Install dependencies
        run: pacman -Syu --noconfirm base-devel cmake clang ninja extra-cmake-modules fmt libuv git python

      - uses: actions/checkout@v6
        with:
          path: fcitx5-mozc
          submodules: recursive


      - name: Expand swap space for Large Dictionary
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Merge and Inject Custom Dictionary
        run: |
          # 14個のファイルを合体（もし末尾に.txtを付けてたら dic_part*.txt に修正してください）
          cat dic_part* > combined_dic.txt
          
          # Mozcの辞書配置場所を特定して上書き
          # ※リポジトリの構造によりますが、一般的なパスを指定しています
          DICTIONARY_PATH="submodules/mozc/src/data/dictionary_oss"
          mkdir -p $DICTIONARY_PATH
          
          # 既存の辞書ファイルを削除して、自作辞書を dictionary00.txt として配置
          rm -f $DICTIONARY_PATH/dictionary0*
          mv combined_dic.txt $DICTIONARY_PATH/dictionary00.txt
          
          echo "Success: Custom dictionary (270MB) has been injected."

      - name: Patch
        working-directory: fcitx5-mozc
        run: |
          git apply --directory=protobuf patches/protobuf.patch
          mkdir -p build/data_manager/oss
          curl -LO --output-dir build/data_manager/oss https://github.com/fcitx-contrib/fcitx5-mozc/releases/download/latest/mozc_data.inc

      - uses: actions/checkout@v6
        with:
          repository: fcitx/fcitx5
          path: fcitx5

      - name: Cache fcitx5 data files
        uses: actions/cache@v5
        with:
          path: 'fcitx5/**/*.tar.*'
          key: ${{ runner.os }}-${{ hashFiles('fcitx5/src/modules/spell/CMakeLists.txt')}}

      - name: Build and Install fcitx5
        uses: fcitx/github-actions@cmake
        with:
          path: fcitx5
          cmake-option: >-
            -DENABLE_KEYBOARD=Off -DENABLE_X11=Off -DENABLE_WAYLAND=Off -DENABLE_ENCHANT=Off
            -DENABLE_DBUS=Off -DENABLE_SERVER=Off -DENABLE_EMOJI=Off -DUSE_SYSTEMD=Off -DENABLE_TEST=OFF -DENABLE_TESTING_ADDONS=OFF

      - name: Build and Install fcitx5-mozc
        uses: fcitx/github-actions@cmake
        with:
          path: fcitx5-mozc

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
